// <auto-generated />
namespace PowerOfGod.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201811181833578_addedMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
